version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: tpdds2025_pdi_grupo9
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tpdds"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - tpnet

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: "prod,postgres"
      DB_HOST: dpg-d32atvodl3ps73fv3v1g-a
      DB_PORT: "5432"
      DB_NAME: tpdds2025_pdi_grupo9
      DB_USER: tpdds2025_pdi_grupo9_user
      DB_PASS: oBC3fVr5pv7wjbuaM2kYfMs3knQVcVBZ
      DDAPI: b72d9e619b345053b742be2d707dec6d
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - tpnet

volumes:
  db_data:

networks:
  tpnet:
